server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: app
  profiles:
    active: development
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem