server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: app
  profiles:
    active: development
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
rsa:
  private-key: ${RSA_PRIVATE_KEY:classpath:certs/private.pem}
  public-key: classpath:certs/public.pem
data-initializer:
  admin-email: ${ADMIN_EMAIL:hexlet@example.com}
  admin-password: ${ADMIN_PASSWORD:qwerty}
sentry:
  dsn: https://ba29868b9c5b4e5c92d42787582ee18a@javaprj99avb.bugsink.com/1
  send-default-pii: true