server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: app
  profiles:
    active: development
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
rsa:
  private-key: ${RSA_PRIVATE_KEY:classpath:certs/private.pem}
  public-key: classpath:certs/public.pem
